version: '3.8'

services:
  app:
    build: .
    ports:
      - "1015:1015"
    volumes:
      - ./service/templates:/app/templates
      - ./service/static:/app/static
    environment:
      - GO_ENV=production
    restart: unless-stopped
    networks:
      - mspd_net

networks:
  mspd_net:
    driver: bridge
